### PR TITLE
Add redirect from master to main

### PR DESCRIPTION
**Pull request by bocon13**

### CODE REVIEW

**Comment by antoninbas** [comment]
doesn't seem to be working, I get a 404

**Comment by antoninbas** [comment]
@bocon13 is there no way to redirect https://p4.org/p4runtime/spec/master/P4Runtime-Spec.html and https://p4.org/p4runtime/spec/master/P4Runtime-Spec.pdf, only https://p4.org/p4runtime/spec/master/ ?

**Comment by bocon13** [comment]
I missed those. Thanks!

The PDF redirect is tricky, let me know if you have another idea:
https://p4.org/p4runtime/spec/master/P4Runtime-Spec.pdf

**Comment by antoninbas** [comment]
Thanks for taking care of this. I think the current solution is fine.

**Pull request merged**
