### PR TITLE
Chrispsommers/redraw figures

### PR DESCRIPTION
**Pull request by chrispsommers**
#21. Redrew all diagrams in OfficeLibre Impress, which is freeware.  The master file is .odg format which can be imported into other programs. It provides basic Visio/PowerPoint-like drawing capabilities. Connector lines are handled quite well which is important for block diagrams. Each image was exported individually in both .png and .svg formats. Madoko's HTML rendering uses .svg and is preferred. LaTex cannot render .svg into the PDF output so .png is specified as a secondary format in the .mdk document source. Note, if need be, the .svg files are importable as master images into other programs.

### CODE REVIEW

**Comment by antoninbas** [comment]
A different idea: we can split all the diagrams in different LibreOffice files, then have the Makefile generate the .svg and .png for all of them using the LibreOffice command-line:
```
soffice --headless --convert-to svg test.odg
soffice --headless --convert-to png test.odg
```

**Comment by chrispsommers** [comment]
@antoninbas , thanks for the careful review, I will fix the errors and discrepancies. I also like your idea to render the images during `make`, I will experiment with that and if I'm satisfied I'll make the changes you proposed and leave the incorporation of `soffice` into the build dockerfile up to you.

**Comment by antoninbas** [comment]
Yes, if the `soffice` command line gives satisfactory results, I'm happy to install `soffice` in the docker

**Comment by antoninbas** [comment]
@chrispsommers when you're ready you can use
```
docker run -v `pwd`/docs/v1:/usr/src/p4-spec p4lang/p4rt-madoko:latest make
```
to build the spec. This new docker image will be used for Travis and includes `soffice`. Let me know if the rendered images look good.

**Comment by chrispsommers** [comment]
@antoninbas I think after you merge https://github.com/p4lang/p4runtime/pull/41 this will build OK and you can merge it in. I already rebased previously, hopefully it can be merged as-is.

**Comment by chrispsommers** [comment]
@antoninbas I've rebased and pushed, CI passed, PTAL at the built docs. Thanks!

**Comment by chrispsommers** [comment]
@antoninbas My pleasure, I think this is a good document workflow model to share with others.

**Pull request merged**
