### PR TITLE
Update version number to 1.0.0-rc2 for release

### PR DESCRIPTION
**Pull request by antoninbas**

### CODE REVIEW

**Comment by antoninbas** [comment]
I am aware that the link to the tagged protos in the spec is different from other references, but I wanted it this way (I wanted the link to show inline).

**Comment by antoninbas** [comment]
Nope, it's a chicken and egg problem :/
Hopefully I got it right, we will know pretty soon

**Comment by antoninbas** [comment]
I got the link right!
Will update the links on p4.org now.

**Comment by chrispsommers** [comment]
Yup, verified it - nice!

**Pull request merged**
