### PR TITLE
Update depdencies to latest versions.

### PR DESCRIPTION
**Pull request by smolkaj**
Fixes https://github.com/p4lang/p4runtime/issues/505.

### CODE REVIEW

**Comment by smolkaj** [comment]
@chrispsommers, this doesn't do anything interesting other than updating a bunch of dependencies. This is often the easiest way to fix sudden build regressions :)

**Comment by chrispsommers** [comment]
Is there any lesson or advice here beyond your comment, which might help posterity?

**Comment by smolkaj** [comment]
The other lesson -- and what very likely triggered this issue -- is that our CI scripts currently use `ubuntu-latest`, which is a moving target. Specifically, in `.github/workflows/ci-build-proto.yml`, we currently have:
```
  build:
    runs-on: ubuntu-latest
```

And, sure enough, `ubuntu-latest` was moved from Ubuntu22.04 to Ubuntu 24.04 2 weeks ago: https://github.com/actions/runner-images/commit/ae99c16b0cf27c0cca7ef0b08e7bcf13c33f6cfa.

It is typical for this to cause regressions, and it is typical that they can be fixed by simply updating all dependencies to their latest versions.

If we wanted, we could use a stable label such as `ubuntu-24.04` instead of the moving label `ubuntu-latest` to avoid such regression. But I actually think this is a healthy forcing function to prevent bit rod, so would prefer to keep things as is.

**Comment by smolkaj** [comment]
Shall we get this merged, @chrispsommers ?

**Review by chrispsommers — APPROVED** [review]

**Pull request merged**
