### PR TITLE
Updating generic-table-dev branch with p4lang:p4runtime:main

### PR DESCRIPTION
**Pull request by saynb**

### CODE REVIEW

**Comment by chrispsommers** [comment]
Hi @saynb I am a bit puzzled why this PR isn't just "sync main to generic-table-dev." It would make the lineage clearer.

**Comment by chrispsommers** [comment]
Understood.

**Review by chrispsommers — APPROVED** [review]
So assuming this makes generic-tables-dev the same as main (hard to tell from the commit chain), LGTM.

**Comment by chrispsommers** [comment]
Merging. @saynb please confirm it resolves to be same as main, otherwise we can fall back to a rebase and force-merge.

**Comment by chrispsommers** [comment]
@saynb got CI build error, even after retry: https://github.com/p4lang/p4runtime/actions/runs/7671762843/job/20910840903#step:5:42

**Comment by saynb** [comment]
@chrispsommers I can confirm that the generic-table-dev branch has no diff with main even if changes show up in a PR if you try and create one from main->generic-table-dev.
Also, this CI job has somehow been failing on main branch itself since last month
https://github.com/p4lang/p4runtime/actions/workflows/ci-build-proto.yml

**Comment by chrispsommers** [comment]
Hi @antoninbas do you have any ideas about the CI failures cited above?

**Comment by antoninbas** [comment]
It's a bazel build issue that I haven't had time to look into.
Looks like the failure is because https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/9e4c622ba8c2178b71420ed3d14fb8874beee3a5.tar.gz no longer exists. Maybe @smolkaj knows what we should be using instead?

**Comment by smolkaj** [comment]
Interesting!

Looks like a regression on the main branch.
Last passing run (10 Dec 2023): https://github.com/p4lang/p4runtime/actions/runs/7161170241
First failing run (11 Dec 2023): https://github.com/p4lang/p4runtime/actions/runs/7174991901

**Comment by smolkaj** [comment]
Here is what changed:
```
2023/12/11 00:10:44 Downloading https://releases.bazel.build/6.4.0/release/bazel-6.4.0-linux-x86_64...
```
vs
```
2023/12/12 00:10:26 Downloading https://releases.bazel.build/7.0.0/release/bazel-7.0.0-linux-x86_64...
```

Looks like we're not yet ready for Bazel 7.x. This is easy to fix by adding a `.bazelversion` file. Let me send a PR.

**Comment by chrispsommers** [comment]
@saynb Could you do another PR to sync to main and gain the benefit of the Bazel fix? Thx.

**Pull request merged**
