### PR TITLE
Fix issue 491 - update changelog for 1.4.0 changes

### PR DESCRIPTION
**Pull request by chrispsommers**
Reviewed all commits since v1.3.0 and ensured every change was mentioned in the change log. Added some structure to categorize the changes.

### CODE REVIEW

**Comment by chrispsommers** [comment]
@jafingerhut @smolkaj could you please take a look? I'm hoping to pave the way for a release before the 4 Workshop.

**Review by smolkaj — APPROVED** [review]
This looks great to me, thanks!

**Comment by chrispsommers** [comment]
@duskmoon314 For some reason, merging in this modest change to .mdk and .md files produced a codecheck failure in the rust generated code. DO you have any idea why this might have happened? Here's the failed job: https://github.com/p4lang/p4runtime/actions/runs/11004409981/job/30555272186

**Comment by duskmoon314** [comment]
Weirdly, running `CI/check_codegen.sh` on the latest commit doesn't fail in my local environment. I need more time to find out why.

**Comment by chrispsommers** [comment]
Thanks for responding so quickly and offering to investigate!

**Comment by duskmoon314** [comment]
I think I found out why.

In the previous PR #500, I only pinned the `protoc-gen-prost/tonic` version. But Cargo ignores the lock file by default. Thus, when building the docker image, `cargo install` will always use the latest version of `protoc-gen-prost/tonic`'s dependencies.

Three days ago, `prost` released a new version. This version changed some generation methods, which is why the CI failed.

I tried adding `--locked` to `cargo install`, which seems to solve this problem. A new PR will be opened soon.

**Comment by duskmoon314** [comment]
#502 is opened to solve the issue. Please review.

I hope this is the last commit to solve this kind version issue. orz

**Pull request merged**
