### PR TITLE
Update generic-table-dev with dev branch workflows

### PR DESCRIPTION
**Pull request by saynb**
Dummy PR to just check whether the changes work on the dev branch. Will be creating a PR for main branch for this change instead

### CODE REVIEW

**Comment by chrispsommers** [comment]
Hi @saynb did you need someone to approve this for test purposes?

**Comment by saynb** [comment]
> Hi @saynb did you need someone to approve this for test purposes?

Hi @chrispsommers , I am still making changes on this and trying out what works and what doesn't with the CI. It will be probably a few tried before it is ready for review and so I converted it to draft. I think CI is able to run even without approvals. Is it fine if I use the same PR for the CI changes and also sync main to this branch?

**Comment by chrispsommers** [comment]
Hi @saynb Do you need any actions/decisions to move this forward? Regarding:
>Would you prefer we make this change only in dev branch or test it here and make the change in main instead

I don't think it matters much either way, but I am in favor of pushing the CI/CD rules changes to main then syncing back to -dev. That way all future -dev branches will gain the benefits if they branch off main. You'd need to make a new PR of course, this one has catchup-commits from main.

Did you test this to your satisfaction?

**Comment by saynb** [comment]
Closing this since have tested this enough and have raised https://github.com/p4lang/p4runtime/pull/443. @chrispsommers FYI

**Pull request closed without merging**
