### PR TITLE
Add note about support of values of type `bool` for table key fields …

### PR DESCRIPTION
**Pull request by jafingerhut**
…etc.

### CODE REVIEW

**Comment by jafingerhut** [comment]
@antoninbas mentioned adding something to the P4Runtime spec similar to this.  Reference: https://github.com/p4lang/p4c/pull/1969#issuecomment-502873598

It needs review, of course, to ensure I have captured the idea correctly.

**Comment by jafingerhut** [comment]
Just a slight warning about possible future consequences of this proposed change:

If the goal in some future P4Runtime version is to enable table search key fields, action parameters, etc. to have more general P4_16 types than the few listed in this section now, e.g. to use P4Data in the way that digest parameters do, then defining `bool` to auto-convert to `bit<1>` like this today could mean that we need to preserve that behavior in the future.  For example, we might have to keep an exception that says "if you want a bool type for action parameters, table search key fields, etc., you must _not_ use P4Data for that, but instead treat it the same as if it were a `bit<1>` type in the P4 program".

**Comment by antoninbas** [comment]
@jafingerhut moving to `P4Data` for match fields and action parameters will be a non backward-compatible change anyway, and that won't happen for a while. Until then boolean value will be treated as `bit<1>` wherever `P4Data` is not used. In places where `P4Data` is already used (digests, registers), the `P4Data` oneof already has a case for boolean values (https://github.com/p4lang/p4runtime/blob/master/proto/p4/v1/p4data.proto#L23).
If, and when, we move to `P4Data` for match fields and action parameters in a future P4Runtime version, then the spec will be updated to say that boolean values are no longer treated as `bit<1>` values. I originally thought that maybe we will have an intermediate version of P4Runtime, which would be backward-compatible, and let you use either `P4Data` or `bytes` for match fields and action parameters. We will see if it is ever needed. So far I'm not sure there has been a use case which requires `P4Data` support for match fields and action parameters. It would definitely be nice to have it and would make the interface more uniform. But it would also make the implementation more complex, and so far there has not been a compelling reason to add this support (either in the form of a backward-compatible version using a `oneof`, or as a non backward-compatible P4Runtime v2.0 release).

**Comment by jafingerhut** [comment]
Regarding this part of the previous comment: "So far I'm not sure there has been a use case which requires P4Data support for match fields and action parameters."

There is the admittedly probably not terribly common scenario of wanting to match on values of type `error`, e.g. in order to convert them to values of type `bit<W>` so they can be put into headers, e.g. to-CPU headers: https://github.com/p4lang/p4-spec/blob/master/p4-16/psa/examples/psa-example-parser-error-handling.p4#L361-L382

An alternate way to handle that use case is to change the P4_16 language spec so that `error` is changed to a serializable enum, perhaps with a target-specific bit width.

**Pull request merged**
