### PR TITLE
Update Go dependencies

### PR DESCRIPTION
**Pull request by antoninbas**

### CODE REVIEW

**Comment by chrispsommers** [comment]
@antoninbas do you intent to signvthe CLA? Thanks.

**Comment by antoninbas** [comment]
> @antoninbas do you intent to signvthe CLA? Thanks.

done

**Comment by chrispsommers** [comment]
See https://github.com/p4lang/p4runtime/pull/437#issuecomment-1622580483 for more deails.

**Review by chrispsommers — APPROVED** [review]
LGTM, thanks Antonin!

**Pull request merged**
